"""지표 정의·실행·정책.

정의는 docs/metric-spec.md, 절차는 docs/statistics-model.md 5~10장, 저장 자리는
docs/erd.md 10장을 따른다. 조합을 전개해 결정적으로 집계하고, 정책 버전이 정한
임계값으로 표본 상태를 판정하며, 저장된 행을 걸러지지 않은 원자 행에서 다시 세어
대조한다. 집계에 생성 모델 호출이 없다.

여덟 모듈이 두 갈래다. `expansion`·`families`·`policy`·`temporal`·`verification` 은
순수 함수이며 저장소를 import 하지 않는다. `runner`·`depth_profile`·`saturation` 은
저장소를 받아 실행 순서를 정한다. 경계는 `tests/unit/test_domain_purity.py` 가
검사한다.

패키지는 유형과 진입점만 내보낸다. 사유 코드와 정책 상수는 모듈에서 직접 import
한다. `NO_ACTIVE_TAXONOMY`·`TAXONOMY_MISMATCH`·`NO_POLICY` 처럼 같은 이름의 사유가
여러 모듈에 있고 `DEPTH_MEASURES` 도 `families` 와 `depth_profile` 에 각각 있어, 한
이름 공간에 모으면 어느 단계의 값인지 읽히지 않는다. 같은 방침을 `graph/__init__.py`
와 `taxonomy/__init__.py` 가 쓴다.
"""

from careersignal.metrics.depth_profile import (
    CapabilityDepth,
    CapabilityDepthProfiles,
    DepthProfileOutcome,
    DimensionDepth,
    confidence_of,
    evidence_support,
    expected_depth,
    merge_dimensions,
    profile_identifier,
    profile_key,
    tail_share,
)
from careersignal.metrics.expansion import (
    Applicability,
    DimensionRef,
    Envelope,
    InputArity,
    MetricCombination,
    MetricFamily,
    MetricTemplate,
    dimension_pairs,
    envelopes,
    expand,
)
from careersignal.metrics.families import (
    MeasureResult,
    advanced_signal_rate,
    cluster_contrast,
    cooccurrence,
    depth_distribution,
    prevalence,
    requiredness,
    scope_expansion,
    segment_labels,
)
from careersignal.metrics.policy import (
    MetricPolicyVersion,
    SampleVerdict,
    classify_pair,
    evaluate,
    policy_from_row,
    same_policy,
    select_policy,
    stores_uncertainty,
    uncertainty_for,
    wilson_interval,
)
from careersignal.metrics.runner import (
    MeasurePoint,
    MetricAggregation,
    MetricOutcome,
    PolicySampler,
    SamplePolicy,
    fact_identifier,
)
from careersignal.metrics.saturation import (
    SaturationObservation,
    SaturationOutcome,
    SaturationSample,
    SaturationTracking,
    SeriesState,
    is_repeat,
    marginal_gain,
    observation_identifier,
    observe,
    observed_at,
)
from careersignal.metrics.temporal import (
    DeltaOutcome,
    MetricPoint,
    Period,
    TemporalDelta,
    delta_measure,
    period_from_row,
    point_from_row,
    temporal_delta,
    temporal_deltas,
)
from careersignal.metrics.verification import (
    AssignmentRow,
    ClusterMembership,
    FactAudit,
    MeasureCount,
    PopulationSpec,
    PopulationUnit,
    Recount,
    StoredFact,
    VersionContext,
    Violation,
    audit_fact,
    audit_facts,
    check_applicability,
    check_deduplication,
    check_denominator,
    check_recount,
    check_sample_status,
    expected_sample_status,
    recount,
)

__all__ = [
    "Applicability",
    "AssignmentRow",
    "CapabilityDepth",
    "CapabilityDepthProfiles",
    "ClusterMembership",
    "DeltaOutcome",
    "DepthProfileOutcome",
    "DimensionDepth",
    "DimensionRef",
    "Envelope",
    "FactAudit",
    "InputArity",
    "MeasureCount",
    "MeasurePoint",
    "MeasureResult",
    "MetricAggregation",
    "MetricCombination",
    "MetricFamily",
    "MetricOutcome",
    "MetricPoint",
    "MetricPolicyVersion",
    "MetricTemplate",
    "Period",
    "PolicySampler",
    "PopulationSpec",
    "PopulationUnit",
    "Recount",
    "SamplePolicy",
    "SampleVerdict",
    "SaturationObservation",
    "SaturationOutcome",
    "SaturationSample",
    "SaturationTracking",
    "SeriesState",
    "StoredFact",
    "TemporalDelta",
    "VersionContext",
    "Violation",
    "advanced_signal_rate",
    "audit_fact",
    "audit_facts",
    "check_applicability",
    "check_deduplication",
    "check_denominator",
    "check_recount",
    "check_sample_status",
    "classify_pair",
    "cluster_contrast",
    "confidence_of",
    "cooccurrence",
    "delta_measure",
    "depth_distribution",
    "dimension_pairs",
    "envelopes",
    "evaluate",
    "evidence_support",
    "expand",
    "expected_depth",
    "expected_sample_status",
    "fact_identifier",
    "is_repeat",
    "marginal_gain",
    "merge_dimensions",
    "observation_identifier",
    "observe",
    "observed_at",
    "period_from_row",
    "point_from_row",
    "policy_from_row",
    "prevalence",
    "profile_identifier",
    "profile_key",
    "recount",
    "requiredness",
    "same_policy",
    "scope_expansion",
    "segment_labels",
    "select_policy",
    "stores_uncertainty",
    "tail_share",
    "temporal_delta",
    "temporal_deltas",
    "uncertainty_for",
    "wilson_interval",
]
