/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#6366f1',
        'primary-light': '#ede9fe',
        'text-primary': '#111',
        'text-secondary': '#6b7280',
        'text-tertiary': '#9ca3af',
        'text-muted': '#374151',
        'bg-primary': '#fff',
        'bg-secondary': '#f8f9fa',
        'bg-tertiary': '#f5f5f5',
        border: '#e5e7eb',
        'border-light': '#f3f4f6',
        success: '#10b981',
        'success-light': '#d1fae5',
        warning: '#f59e0b',
        'warning-light': '#fef3c7',
        danger: '#ef4444',
        'danger-light': '#fee2e2',
      },
      fontSize: {
        xs: '10px',
        sm: '11px',
        base: '12px',
        md: '13px',
        lg: '14px',
        xl: '15px',
        '2xl': '18px',
        '3xl': '22px',
        '4xl': '28px',
      },
      fontWeight: {
        regular: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
      spacing: {
        0: '0',
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
      },
      borderRadius: {
        0: '0',
        1: '2px',
        2: '4px',
        3: '6px',
        4: '8px',
        6: '12px',
        9999: '9999px',
      },
    },
  },
  plugins: [],
}
