services:
  db:
    image: postgres:16-alpine
    container_name: hub-db
    environment:
      POSTGRES_USER: rbgus    
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: hub
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
