// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // 마이그레이션(CLI)은 Supabase pooler를 거치지 않는 직결 연결(DIRECT_URL)을 쓴다.
  // 런타임 쿼리용 DATABASE_URL(pooler)은 src/lib/prisma.js에서 별도로 사용한다.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
