"""합격 전략 에이전트.

정의는 docs/agent-design.md 7.5 를 따른다. 해석 산출물이 세운 기준선과 편차 위에
체크리스트를 만들고, 각 항목을 자기소개서·포트폴리오·면접에 배정한다.

체크리스트는 개념과 버전 인스턴스를 분리해 저장한다. 사용자 체크 상태는 개념
식별자에 연결되므로 문구가 바뀌어도 살아남는다.
"""

from careersignal.agents.strategy.adapter import (
    OpenAIStrategyWriter,
    StubStrategyWriter,
)
from careersignal.agents.strategy.agent import (
    BASELINE_KICKER,
    INTRO_ORDER_STEPS,
    OUTPUT_TYPE,
    OVERALL_CLUSTER_LABEL,
    PRODUCED_BY,
    STUDY_KICKER,
    StrategyPlanner,
    build_payload,
)
from careersignal.agents.strategy.checklist import (
    CHANNEL_ORDER,
    DISALLOWED_TIER,
    MISSING_EVIDENCE,
    PRIMARY_CHANNEL,
    REQUIRED_RATIO_THRESHOLD,
    STRATEGY_USE,
    assign_channels,
    blocked_concepts,
    concept_identifier,
    concept_of,
    draft_checklist,
    evidence_checks,
    item_identifier,
    item_of,
    output_identifier,
    policy_violations,
    scope_key,
    slugify,
    surviving_checks,
    unlinked,
    version_marker,
)
from careersignal.agents.strategy.contract import (
    AGENT_VERSION,
    STORED,
    BaselineRequirement,
    Channel,
    ChecklistConcept,
    ChecklistCopy,
    ChecklistDraft,
    ChecklistItem,
    ChecklistKind,
    Confidence,
    DeviationSignal,
    EvidenceKind,
    EvidenceLink,
    InterpretationInput,
    StrategyOutcome,
    StrategyRepository,
    StrategyWriter,
)
from careersignal.agents.strategy.prompts import (
    CHANNEL_GUIDE,
    STRATEGY_COPY_PROMPT,
    STRATEGY_RESPONSE_SCHEMA,
    STRATEGY_TASK,
)

__all__ = [
    "AGENT_VERSION",
    "BASELINE_KICKER",
    "BaselineRequirement",
    "CHANNEL_GUIDE",
    "CHANNEL_ORDER",
    "Channel",
    "ChecklistConcept",
    "ChecklistCopy",
    "ChecklistDraft",
    "ChecklistItem",
    "ChecklistKind",
    "Confidence",
    "DISALLOWED_TIER",
    "DeviationSignal",
    "EvidenceKind",
    "EvidenceLink",
    "INTRO_ORDER_STEPS",
    "InterpretationInput",
    "MISSING_EVIDENCE",
    "OUTPUT_TYPE",
    "OVERALL_CLUSTER_LABEL",
    "OpenAIStrategyWriter",
    "PRIMARY_CHANNEL",
    "PRODUCED_BY",
    "REQUIRED_RATIO_THRESHOLD",
    "STORED",
    "STRATEGY_COPY_PROMPT",
    "STRATEGY_RESPONSE_SCHEMA",
    "STRATEGY_TASK",
    "STRATEGY_USE",
    "STUDY_KICKER",
    "StrategyOutcome",
    "StrategyPlanner",
    "StrategyRepository",
    "StrategyWriter",
    "StubStrategyWriter",
    "assign_channels",
    "blocked_concepts",
    "build_payload",
    "concept_identifier",
    "concept_of",
    "draft_checklist",
    "evidence_checks",
    "item_identifier",
    "item_of",
    "output_identifier",
    "policy_violations",
    "scope_key",
    "slugify",
    "surviving_checks",
    "unlinked",
    "version_marker",
]
