'use server';
import { revalidatePath } from 'next/cache';
import type { ActionState } from '../errors/action-state';
import { toActionState } from '../errors/domain-error-map';
import { requireSession } from '../auth/session';
import { getCoreAdapter } from '../adapters/core/registry';
import { getServerEnv } from '../config/server-env';
import { validateEvidence } from '../storage/evidence-validation';
import { buildEvidencePath, parseEvidencePath } from '../storage/evidence-path';
import { getServerSupabaseClient } from '../lib/supabase/server';
export async function submitDailyGoalAction(_previous: ActionState, formData: FormData): Promise<ActionState> { const participationId = String(formData.get('participationId') ?? ''); const date = String(formData.get('date') ?? ''); const goal = String(formData.get('goal') ?? '').trim(); if (goal.length < 2 || goal.length > 300) return { status: 'error', message: '목표를 2–300자로 입력해 주세요.' }; const ctx = await requireSession(`/study/${participationId}`); const result = await getCoreAdapter().submitDailyGoal(ctx, { participationId, date, goal }); if (!result.ok) return toActionState(result.error); revalidatePath(`/study/${participationId}`); return { status: 'success', message: '오늘의 목표를 저장했습니다.' }; }
export async function recordTimerSessionAction(_previous: ActionState, formData: FormData): Promise<ActionState> { const participationId = String(formData.get('participationId') ?? ''); const date = String(formData.get('date') ?? ''); const elapsedSeconds = Number(formData.get('elapsedSeconds')); const clientSessionId = String(formData.get('clientSessionId') ?? ''); if (!Number.isInteger(elapsedSeconds) || elapsedSeconds <= 0 || !clientSessionId) return { status: 'error', message: '기록할 학습 시간이 없습니다.' }; const ctx = await requireSession(`/study/${participationId}`); const result = await getCoreAdapter().recordTimerSession(ctx, { participationId, date, elapsedSeconds, clientSessionId }); if (!result.ok) return toActionState(result.error); revalidatePath(`/study/${participationId}`); return { status: 'success', message: `${elapsedSeconds}초를 확정 기록했습니다.` }; }
export async function createEvidenceUploadAction(_previous: ActionState, formData: FormData): Promise<ActionState> { const participationId = String(formData.get('participationId') ?? ''); const date = String(formData.get('date') ?? ''); const type = String(formData.get('type') ?? ''); const size = Number(formData.get('size')); const env = getServerEnv(); const validation = validateEvidence({ type, size }, env.evidenceMimeTypes, env.evidenceMaxBytes); if (validation) return { status: 'error', message: validation }; const ctx = await requireSession(`/study/${participationId}`); const authorization = await getCoreAdapter().authorizeEvidenceUpload(ctx, { participationId, date }); if (!authorization.ok) return toActionState(authorization.error); const owner = authorization.value; let path: string; try { path = buildEvidencePath({ userId: owner.userId, challengeId: owner.challengeId, date: owner.date, fileId: crypto.randomUUID() }); } catch { return { status: 'error', message: 'Core의 증빙 경로 계약이 아직 준비되지 않았습니다.' }; } const client = await getServerSupabaseClient(); if (!client) return { status: 'error', message: '파일 저장소가 구성되지 않았습니다.', data: { evidencePath: path } }; const { data, error } = await client.storage.from('evidence').createSignedUploadUrl(path); if (error) return { status: 'error', message: '업로드 주소를 만들지 못했습니다.' }; return { status: 'success', message: '업로드 주소를 준비했습니다.', data: { evidencePath: path, signedUrl: data.signedUrl, token: data.token } }; }
export async function submitVerificationAction(_previous: ActionState, formData: FormData): Promise<ActionState> { const participationId = String(formData.get('participationId') ?? ''); const date = String(formData.get('date') ?? ''); const retrospective = String(formData.get('retrospective') ?? '').trim(); const evidencePath = String(formData.get('evidencePath') ?? ''); if (retrospective.length < 10 || !evidencePath) return { status: 'error', message: '10자 이상의 회고와 업로드된 증빙이 필요합니다.' }; const ctx = await requireSession(`/study/${participationId}`); const result = await getCoreAdapter().submitVerification(ctx, { participationId, date, retrospective, evidencePath }); if (!result.ok) return toActionState(result.error); revalidatePath(`/study/${participationId}`); return { status: 'success', message: '오늘의 생존 인증이 완료되었습니다.' }; }
export async function createEvidenceViewAction(_previous: ActionState, formData: FormData): Promise<ActionState> { const participationId = String(formData.get('participationId') ?? ''); const evidencePath = String(formData.get('evidencePath') ?? ''); const parsed = parseEvidencePath(evidencePath); if (!parsed) return { status: 'error', message: '올바르지 않은 증빙 경로입니다.' }; const ctx = await requireSession(`/study/${participationId}`); const authorization = await getCoreAdapter().authorizeEvidenceUpload(ctx, { participationId, date: parsed.date }); if (!authorization.ok) return toActionState(authorization.error); if (authorization.value.userId !== parsed.userId || authorization.value.challengeId !== parsed.challengeId || authorization.value.date !== parsed.date) return { status: 'error', message: '이 증빙을 볼 권한이 없습니다.' }; const client = await getServerSupabaseClient(); if (!client) return { status: 'error', message: '파일 저장소가 구성되지 않았습니다.' }; const { data, error } = await client.storage.from('evidence').createSignedUrl(evidencePath, 60); if (error) return { status: 'error', message: '증빙 보기 주소를 만들지 못했습니다.' }; return { status: 'success', message: '60초 동안 사용할 수 있는 보기 주소입니다.', data: { signedUrl: data.signedUrl } }; }
export async function refreshAction(): Promise<void> { 'use server'; }
