export const colors = {
  primary: '#2563EB',
  primaryTint: '#EFF6FF',
  primaryBorder: '#DBEAFE',
  success: '#15803D',
  successTint: '#F0FDF4',
  danger: '#DC2626',
  dangerTint: '#FEF2F2',
  dangerBorder: '#FECACA',
  warning: '#B45309',
  warningTint: '#FFFBEB',
  bgPrimary: '#F8FAFC',
  bgCard: '#FFFFFF',
  borderColor: '#E2E8F0',
  textPrimary: '#0F172A',
  textSecondary: '#475569',
  textTertiary: '#94A3B8',
  chartHighlight: '#2563EB',
  chartSecondary: '#93C5FD',
  chartLight: '#EFF2F7',
};
