// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig } from 'prisma/config'

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'node prisma/seed.js',
  },
  datasource: {
    // 마이그레이션은 advisory lock이 필요해 세션모드 풀러(DIRECT_URL)를 쓴다.
    // 앱 런타임의 PrismaClient는 트랜잭션모드 풀러(DATABASE_URL)를 따로 지정해서 쓴다.
    url: process.env['DIRECT_URL'],
  },
})
