// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsAVn5q8Rg4SVW4gEKGFx-iJt5oVkLcyw',
    appId: '1:642470930772:web:9d23e4219d7eb5ec5440c1',
    messagingSenderId: '642470930772',
    projectId: 'one-step-16073',
    authDomain: 'one-step-16073.firebaseapp.com',
    storageBucket: 'one-step-16073.firebasestorage.app',
    measurementId: 'G-X61ED2DHL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVkLOBhwmdg7ah5ha5o_YQvVMc_wa6qns',
    appId: '1:642470930772:android:cf20bd7c6c94af755440c1',
    messagingSenderId: '642470930772',
    projectId: 'one-step-16073',
    storageBucket: 'one-step-16073.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANgOyk-Uir0xGCqj4dA21ivT0x52VVMbY',
    appId: '1:642470930772:ios:93f1f58e972941855440c1',
    messagingSenderId: '642470930772',
    projectId: 'one-step-16073',
    storageBucket: 'one-step-16073.firebasestorage.app',
    iosBundleId: 'com.onestep.oneStep',
  );
}
