import type { Mode, PurposeId, ScenarioId } from '../../../src/entities/message/index.js'
import type { GeneratedCandidate } from '../../../src/shared/generation/contracts.js'
import type { ReviewedPromptExampleSet } from '../prompt/examples.js'

export const retrievalCoverageDraftCatalogVersion = 'retrieval-coverage-draft-2026-07-22.1'

export type RetrievalCoverageDraftExampleSet = ReviewedPromptExampleSet & {
  readonly reviewStatus: 'draft'
}

type DraftInput = {
  readonly candidates: readonly GeneratedCandidate[]
  readonly exampleId: string
  readonly mode: Mode
  readonly purpose: PurposeId
  readonly receivedMessage?: string
  readonly scenarioId: ScenarioId
  readonly situation: string
}

const tones = (basic: string, softer: string, clearer: string) =>
  [
    { toneLevel: 1, text: basic },
    { toneLevel: 2, text: softer },
    { toneLevel: 3, text: clearer },
  ] as const satisfies readonly GeneratedCandidate[]

const draftExample = (input: DraftInput): RetrievalCoverageDraftExampleSet => ({
  ...input,
  catalogVersion: retrievalCoverageDraftCatalogVersion,
  reviewStatus: 'draft',
})

const groupworkDraftExamples = [
  draftExample({
    exampleId: 'draft-groupwork-reply-ask-02',
    mode: 'reply',
    scenarioId: 'groupwork',
    purpose: 'ask',
    situation:
      '필요한 자료가 무엇인지 묻는 팀원에게 각자 사용한 참고 자료와 출처 링크를 공유 폴더에 올려 달라고 부탁함',
    receivedMessage: '참고할 자료 어떤 거 필요해?',
    candidates: tones(
      '각자 사용한 참고 자료를 공유 폴더에 올려주면 돼. 출처를 확인할 수 있게 링크도 같이 남겨줘.',
      '각자 사용한 참고 자료를 공유 폴더에 올려줄 수 있을까? 출처를 확인할 수 있게 링크도 같이 남겨주면 고마워!',
      '각자 사용한 참고 자료와 출처 링크를 공유 폴더에 올려줘.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-initiate-ask-01',
    mode: 'initiate',
    scenarioId: 'groupwork',
    purpose: 'ask',
    situation: '발표 자료를 합치기 전에 팀원들에게 각자 만든 슬라이드를 한 번씩 교차 검토해 달라고 부탁함',
    candidates: tones(
      '발표 자료 합치기 전에 각자 만든 슬라이드를 한 번씩 서로 검토해 줬으면 해. 확인한 부분은 댓글로 남겨줘!',
      '발표 자료를 합치기 전에 혹시 각자 만든 슬라이드를 한 번씩 서로 봐줄 수 있을까? 확인한 부분은 댓글로 남겨주면 고마워!',
      '발표 자료 합치기 전에 각자 슬라이드를 한 번씩 교차 검토해 줘. 수정할 부분은 댓글로 남겨줘.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-initiate-ask-02',
    mode: 'initiate',
    scenarioId: 'groupwork',
    purpose: 'ask',
    situation: '출처를 정리하기 위해 팀원들에게 각자 사용한 참고 링크를 공유 문서에 남겨 달라고 부탁함',
    candidates: tones(
      '출처 정리하려고 해. 각자 사용한 참고 링크를 공유 문서에 남겨줘!',
      '출처를 한 번에 정리하려고 하는데, 각자 사용한 참고 링크를 공유 문서에 남겨줄 수 있을까?',
      '각자 사용한 참고 링크를 공유 문서에 남겨줘. 그 목록으로 출처를 정리할게.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-reply-apologize-01',
    mode: 'reply',
    scenarioId: 'groupwork',
    purpose: 'apologize',
    situation: '단체방 확인이 늦다는 팀원의 지적을 받고 확인과 답장이 늦은 사실을 인정해 사과함',
    receivedMessage: '단체방 확인이 너무 늦는 거 아니야? 답이 없어서 기다렸어.',
    candidates: tones(
      '맞아, 내가 단체방 확인이 늦었어. 기다리게 해서 미안해. 지금부터 바로 확인할게.',
      '내가 단체방을 늦게 확인했어. 답 기다렸을 텐데 미안해. 지금부터 바로 확인할게!',
      '단체방 확인이 늦은 건 내 잘못이야. 기다리게 해서 미안해. 지금 확인할게.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-reply-apologize-02',
    mode: 'reply',
    scenarioId: 'groupwork',
    purpose: 'apologize',
    situation: '보낸 파일 링크가 잘못됐다는 팀원의 말을 받고 혼선을 준 점을 사과하고 올바른 링크를 다시 보냄',
    receivedMessage: '네가 보낸 링크 열어 보니까 다른 파일이 나오는데?',
    candidates: tones(
      '내가 링크를 잘못 보냈어. 헷갈리게 해서 미안해. 올바른 링크로 다시 보낼게.',
      '앗, 내가 링크를 잘못 보냈어. 확인하느라 번거로웠을 텐데 미안해! 올바른 링크로 다시 보낼게.',
      '링크를 잘못 보냈어. 혼선 줘서 미안해. 올바른 링크로 다시 보낼게.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-initiate-apologize-01',
    mode: 'initiate',
    scenarioId: 'groupwork',
    purpose: 'apologize',
    situation: '단체방 메시지를 늦게 확인해 팀원들에게 답장이 늦어진 점을 먼저 사과함',
    candidates: tones(
      '단체방 메시지를 이제 확인했어. 답이 늦어서 미안해. 올라온 내용부터 확인할게.',
      '단체방 메시지를 늦게 확인했어. 기다렸을 텐데 답이 늦어서 미안해! 올라온 내용부터 확인할게.',
      '단체방 확인이 늦었어. 답이 늦어서 미안해. 지금 내용 확인할게.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-initiate-apologize-02',
    mode: 'initiate',
    scenarioId: 'groupwork',
    purpose: 'apologize',
    situation: '공유 문서에서 다른 팀원이 작성한 내용을 실수로 수정한 사실을 확인하고 먼저 사과함',
    candidates: tones(
      '공유 문서 확인하다가 내가 다른 사람이 작성한 부분을 실수로 수정한 걸 발견했어. 미안해. 수정 전 내용으로 되돌려 놓을게.',
      '공유 문서를 보다가 내가 다른 사람이 작성한 부분을 잘못 건드린 걸 발견했어. 당황했을 텐데 미안해! 수정 전 내용으로 되돌려 놓을게.',
      '내가 공유 문서의 다른 사람 작성 부분을 실수로 수정했어. 미안해. 바로 이전 내용으로 복구할게.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-reply-decline-01',
    mode: 'reply',
    scenarioId: 'groupwork',
    purpose: 'decline',
    situation: '이미 맡은 역할이 있는 상태에서 팀원이 추가 역할까지 맡아 달라고 부탁해 현재 역할 외 추가 업무는 거절함',
    receivedMessage: '지금 맡은 것 말고 발표 대본도 같이 써줄 수 있어?',
    candidates: tones(
      '지금 맡은 파트를 마무리해야 해서 발표 대본까지 맡기는 어려울 것 같아. 이번에는 지금 역할에 집중할게.',
      '내가 지금 맡은 파트를 먼저 마무리해야 해서 발표 대본까지 맡기는 어려울 것 같아. 미안하지만 이번에는 지금 역할에 집중해도 될까?',
      '발표 대본까지는 맡기 어려워. 지금 맡은 파트에 집중할게.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-reply-decline-02',
    mode: 'reply',
    scenarioId: 'groupwork',
    purpose: 'decline',
    situation: '팀원이 제안한 회의 시간에는 참여하기 어려워 해당 시간의 참석을 거절함',
    receivedMessage: '오늘 저녁에 바로 회의하는 거 어때?',
    candidates: tones(
      '오늘 저녁에는 참여하기 어려워서 그 시간 회의는 힘들 것 같아.',
      '미안하지만 오늘 저녁에는 참여하기 어려워서 그 시간 회의는 힘들 것 같아.',
      '오늘 저녁 회의에는 참여하기 어려워.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-initiate-decline-01',
    mode: 'initiate',
    scenarioId: 'groupwork',
    purpose: 'decline',
    situation: '역할 배분안이 확정되기 전에 자신에게 추가된 업무는 맡기 어렵다는 의견을 먼저 알림',
    candidates: tones(
      '역할 배분안 확인했어. 지금 맡은 업무 외에 추가된 부분까지는 맡기 어려울 것 같아서 확정 전에 알려.',
      '역할 배분안 확인했어. 미안하지만 지금 맡은 업무 외에 추가된 부분까지는 맡기 어려울 것 같아서 확정 전에 먼저 말해둘게.',
      '역할 배분안의 추가 업무는 맡기 어려워. 확정 전에 반영해 줘.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-initiate-decline-02',
    mode: 'initiate',
    scenarioId: 'groupwork',
    purpose: 'decline',
    situation: '일정 투표가 확정되기 전에 제시된 후보 시간에는 참여하기 어렵다고 먼저 알림',
    candidates: tones(
      '일정 확정 전에 알려. 지금 올라온 후보 시간에는 참여하기 어려워.',
      '일정 확정 전에 미리 말해둘게. 미안하지만 지금 올라온 후보 시간에는 참여하기 어려울 것 같아.',
      '지금 올라온 후보 시간에는 참여하기 어려워. 일정 확정 전에 알려.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-reply-question-01',
    mode: 'reply',
    scenarioId: 'groupwork',
    purpose: 'question',
    situation: '팀원이 맡을 범위를 모호하게 전달해 자신이 포함해야 할 결과물이 무엇인지 다시 물음',
    receivedMessage: '너는 자료 정리 쪽 맡아주면 될 것 같아.',
    candidates: tones(
      '자료 정리 범위가 어디까지인지 확인하고 싶어. 출처 목록이랑 요약문까지 포함하면 될까?',
      '자료 정리 범위를 정확히 확인하고 싶은데, 혹시 출처 목록이랑 요약문까지 포함하면 될까?',
      '자료 정리에는 출처 목록과 요약문까지 포함하면 되는지 알려줘.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-reply-question-02',
    mode: 'reply',
    scenarioId: 'groupwork',
    purpose: 'question',
    situation: '사용 가능한 자료 기준을 전달받았지만 출처 표기 방식이 불분명해 구체적인 표기 형식을 물음',
    receivedMessage: '공식 자료 위주로 쓰고 출처는 꼭 적어줘.',
    candidates: tones(
      '출처 표기 방식도 맞추려고 하는데, 본문 각주로 달면 되는지 마지막에 목록으로 정리하면 되는지 알려줄래?',
      '출처 표기 방식도 통일하면 좋을 것 같아. 혹시 본문 각주로 달면 될지, 마지막에 목록으로 정리하면 될지 알려줄 수 있을까?',
      '출처는 본문 각주와 마지막 목록 중 어떤 방식으로 표기할지 알려줘.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-initiate-question-01',
    mode: 'initiate',
    scenarioId: 'groupwork',
    purpose: 'question',
    situation: '각 팀원에게 맡은 파트의 현재 진행 상태와 막힌 점이 있는지 먼저 물음',
    candidates: tones(
      '각자 맡은 파트 지금 어디까지 진행됐는지랑 막힌 부분이 있는지 알려줘.',
      '진행 상황 한번 맞춰보면 좋을 것 같아. 각자 맡은 파트가 어디까지 됐는지, 막힌 부분이 있는지 알려줄 수 있을까?',
      '각자 맡은 파트의 진행 상태와 막힌 점을 알려줘.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-initiate-question-02',
    mode: 'initiate',
    scenarioId: 'groupwork',
    purpose: 'question',
    situation: '최종 제출 전에 파일 형식과 제출 담당자가 어떻게 정해졌는지 확인함',
    candidates: tones(
      '최종 제출 전에 확인하려고 해. 파일 형식은 뭘로 맞추고 누가 제출하기로 했어?',
      '최종 제출 전에 헷갈리지 않게 확인하고 싶은데, 파일 형식은 뭘로 맞추고 누가 제출하기로 했는지 알려줄 수 있을까?',
      '최종 파일 형식과 제출 담당자가 누구인지 알려줘.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-reply-suggest-01',
    mode: 'reply',
    scenarioId: 'groupwork',
    purpose: 'suggest',
    situation: '팀원이 제안한 회의 시간이 어려워 다음 날 오후라는 다른 후보를 제안함',
    receivedMessage: '오늘 밤에 회의할 수 있어?',
    candidates: tones(
      '오늘 밤은 어려워. 대신 내일 오후에 회의하는 건 어때?',
      '오늘 밤은 조금 어려울 것 같아. 괜찮다면 내일 오후에 회의하는 건 어떨까?',
      '오늘 밤은 안 되고 내일 오후는 가능해. 내일 오후로 정하는 걸 제안할게.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-reply-suggest-02',
    mode: 'reply',
    scenarioId: 'groupwork',
    purpose: 'suggest',
    situation: '역할이 한 사람에게 몰린다는 팀원의 의견을 받고 현재 업무를 다시 나누는 방식을 제안함',
    receivedMessage: '지금 역할이 한 사람한테 너무 몰린 것 같아.',
    candidates: tones(
      '맞아, 지금 업무를 한 번 더 나눠보자. 각자 가능한 범위를 먼저 적고 그걸 기준으로 다시 배분하면 좋겠어.',
      '나도 역할이 몰린 것 같아. 괜찮다면 각자 가능한 범위를 먼저 적고 그걸 기준으로 다시 나눠보는 건 어때?',
      '업무를 다시 나누자. 각자 가능한 범위를 적고 그 기준으로 재배분하면 돼.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-initiate-suggest-02',
    mode: 'initiate',
    scenarioId: 'groupwork',
    purpose: 'suggest',
    situation: '각자 작성한 결과를 마지막에 한 번에 합치지 않고 중간본을 먼저 공유해 함께 검토하자고 제안함',
    candidates: tones(
      '마지막에 한 번에 합치기보다 각자 중간본을 먼저 공유하고 같이 검토하는 게 좋을 것 같아.',
      '마지막에 한 번에 합치면 수정이 많을 수 있으니까, 괜찮다면 각자 중간본을 먼저 공유하고 같이 검토해 보는 건 어때?',
      '각자 중간본을 먼저 공유하고 같이 검토하자. 마지막에 한 번에 합치는 방식은 피했으면 해.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-reply-other-01',
    mode: 'reply',
    scenarioId: 'groupwork',
    purpose: 'other',
    situation: '팀원이 참고 자료를 공유해 준 메시지에 자료를 확인했다는 말과 감사를 전함',
    receivedMessage: '찾은 참고 자료 공유 폴더에 올려뒀어!',
    candidates: tones(
      '자료 확인했어. 정리해서 올려줘서 고마워!',
      '자료 확인했어! 찾고 정리하느라 수고했을 텐데 올려줘서 정말 고마워.',
      '자료 확인했어. 공유해 줘서 고마워.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-reply-other-02',
    mode: 'reply',
    scenarioId: 'groupwork',
    purpose: 'other',
    situation: '팀원이 진행 상황을 알려 준 답장에 전달한 내용을 확인했다고 짧게 알림',
    receivedMessage: '내 파트는 초안까지 끝냈고 지금 자료 보충하고 있어.',
    candidates: tones(
      '응, 진행 상황 확인했어. 알려줘서 고마워.',
      '응, 어디까지 진행됐는지 확인했어! 정리해서 알려줘서 고마워.',
      '진행 상황 확인했어. 알려줘서 고마워.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-initiate-other-01',
    mode: 'initiate',
    scenarioId: 'groupwork',
    purpose: 'other',
    situation: '자신이 맡은 파트의 초안을 끝냈고 자료를 보완하고 있다는 현재 진행 상태를 팀원들에게 먼저 공유함',
    candidates: tones(
      '내가 맡은 파트는 초안까지 끝냈고 지금 자료를 보완하고 있어. 진행 상황 공유해!',
      '내가 맡은 파트는 초안까지 마쳤고 지금 자료를 보완하고 있어. 참고할 수 있게 진행 상황 먼저 공유할게!',
      '내 파트는 초안 완료했고 자료 보완 중이야. 진행 상황 공유해.',
    ),
  }),
  draftExample({
    exampleId: 'draft-groupwork-initiate-other-02',
    mode: 'initiate',
    scenarioId: 'groupwork',
    purpose: 'other',
    situation: '프로젝트가 끝난 뒤 함께 작업한 팀원들에게 수고했다는 말과 감사를 먼저 전함',
    candidates: tones(
      '다들 프로젝트 하느라 수고 많았어. 같이 끝까지 해줘서 고마워!',
      '다들 프로젝트 하는 동안 정말 수고 많았어. 같이 맞춰가며 끝까지 해줘서 고마워!',
      '프로젝트 끝까지 함께해 줘서 고마워. 다들 수고했어.',
    ),
  }),
] as const satisfies readonly RetrievalCoverageDraftExampleSet[]

const professorDraftExamples = [
  draftExample({
    exampleId: 'draft-professor-reply-ask-01',
    mode: 'reply',
    scenarioId: 'professor',
    purpose: 'ask',
    situation: '조교가 누락된 자료를 다시 보내 달라고 안내해 파일을 재전송하면서 수신 확인을 부탁드림',
    receivedMessage: '첨부 자료가 확인되지 않습니다. 파일을 다시 보내주시기 바랍니다.',
    candidates: tones(
      '조교님 안녕하세요. 안내해 주신 파일을 다시 첨부해 보내드립니다. 정상적으로 확인되는지 회신 부탁드립니다. 감사합니다.',
      '조교님 안녕하세요. 첨부가 누락되어 번거롭게 해드려 죄송합니다. 안내해 주신 파일을 다시 보내드리니, 확인 가능하실 때 정상적으로 열리는지 알려주시면 감사하겠습니다. 감사합니다.',
      '조교님 안녕하세요. 누락된 파일을 다시 첨부했습니다. 정상적으로 확인되는지 회신 부탁드립니다. 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-reply-ask-02',
    mode: 'reply',
    scenarioId: 'professor',
    purpose: 'ask',
    situation: '교수님이 면담 가능한 시간을 알려 달라고 답해 자신이 제시한 두 후보 중 하나로 확정해 달라고 부탁드림',
    receivedMessage: '면담 가능한 시간을 몇 가지 알려주면 확인해 보겠습니다.',
    candidates: tones(
      '교수님 안녕하세요. 저는 화요일 오후 2시와 목요일 오전 11시에 가능합니다. 두 시간 중 편하신 때로 확정해 주시면 감사하겠습니다. 감사합니다.',
      '교수님 안녕하세요. 면담 시간을 확인해 주셔서 감사합니다. 저는 화요일 오후 2시와 목요일 오전 11시에 가능하니, 두 시간 중 편하신 때로 정해 주시면 감사하겠습니다. 감사합니다.',
      '교수님 안녕하세요. 화요일 오후 2시와 목요일 오전 11시에 가능합니다. 가능한 시간으로 확정 부탁드립니다. 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-initiate-ask-01',
    mode: 'initiate',
    scenarioId: 'professor',
    purpose: 'ask',
    situation: '수업 내용과 관련해 교수님께 짧은 면담을 통해 조언을 구할 수 있는지 부탁드림',
    candidates: tones(
      '교수님 안녕하세요. 수업 내용을 공부하면서 방향을 여쭙고 싶은 부분이 있어 연락드립니다. 가능하시다면 짧게 면담하며 조언을 구하고 싶습니다. 감사합니다.',
      '교수님 안녕하세요. 수업 내용을 공부하던 중 혼자 판단하기 어려운 부분이 있어 조심스럽게 연락드립니다. 혹시 가능하실 때 짧게 면담하며 조언을 구할 수 있을지 여쭙습니다. 감사합니다.',
      '교수님 안녕하세요. 수업 내용과 관련해 조언을 구하고 싶습니다. 짧은 면담이 가능하신지 답변 부탁드립니다. 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-initiate-ask-02',
    mode: 'initiate',
    scenarioId: 'professor',
    purpose: 'ask',
    situation: '작성한 과제 초안의 방향이 적절한지 교수님께 간단한 검토가 가능한지 부탁드림',
    candidates: tones(
      '교수님 안녕하세요. 과제 초안을 작성했는데 전체 방향이 적절한지 확인받고 싶어 연락드립니다. 가능하시다면 간단히 검토해 주실 수 있을지 부탁드립니다. 감사합니다.',
      '교수님 안녕하세요. 과제 초안을 작성한 뒤 방향을 제대로 잡았는지 확신이 서지 않아 조심스럽게 여쭙습니다. 시간 괜찮으실 때 전체 방향만이라도 간단히 검토해 주실 수 있을까요? 감사합니다.',
      '교수님 안녕하세요. 작성한 과제 초안의 방향을 확인받고 싶습니다. 간단한 검토가 가능하신지 답변 부탁드립니다. 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-reply-apologize-01',
    mode: 'reply',
    scenarioId: 'professor',
    purpose: 'apologize',
    situation: '교수님에게 회신이 늦었다는 연락을 받고 답장이 늦은 사실을 인정해 사과드림',
    receivedMessage: '확인이 필요한 내용인데 아직 답장이 없어 다시 연락합니다.',
    candidates: tones(
      '교수님 안녕하세요. 메일을 확인하고도 회신이 늦었습니다. 답변을 기다리게 해드려 죄송합니다. 지금 확인한 내용으로 바로 회신드리겠습니다.',
      '교수님 안녕하세요. 확인이 필요한 메일에 제때 답변드리지 못해 죄송합니다. 기다리셨을 텐데 회신이 늦어진 점 다시 한번 사과드립니다. 지금 확인한 내용으로 바로 회신드리겠습니다.',
      '교수님 안녕하세요. 회신이 늦어 죄송합니다. 지금 확인한 내용으로 바로 답변드리겠습니다. 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-reply-apologize-02',
    mode: 'reply',
    scenarioId: 'professor',
    purpose: 'apologize',
    situation: '첨부가 빠졌다는 조교의 안내를 받고 파일 누락과 재확인 수고에 대해 사과드림',
    receivedMessage: '보내주신 메일에 첨부 파일이 없습니다. 확인해 주세요.',
    candidates: tones(
      '조교님 안녕하세요. 제가 파일을 첨부하지 않고 메일을 보냈습니다. 다시 확인하시게 해드려 죄송합니다. 파일을 첨부해 다시 보내드리겠습니다.',
      '조교님 안녕하세요. 확인해 보니 제가 파일을 누락한 채 메일을 보냈습니다. 번거롭게 다시 확인하시게 해드려 죄송합니다. 파일을 첨부해 다시 보내드리겠습니다.',
      '조교님 안녕하세요. 첨부 파일을 누락해 죄송합니다. 파일을 첨부해 다시 보내드리겠습니다. 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-initiate-apologize-01',
    mode: 'initiate',
    scenarioId: 'professor',
    purpose: 'apologize',
    situation: '교수님에게 받은 메일을 확인하고도 제때 답하지 못한 점을 먼저 사과드림',
    candidates: tones(
      '교수님 안녕하세요. 보내주신 메일을 확인하고도 회신을 제때 드리지 못했습니다. 답변이 늦어진 점 죄송합니다. 지금 확인한 내용을 정리해 회신드립니다.',
      '교수님 안녕하세요. 보내주신 메일을 확인했음에도 바로 답변드리지 못해 죄송합니다. 기다리셨을 수 있는데 회신이 늦어진 점 사과드립니다. 지금 확인한 내용을 정리해 회신드립니다.',
      '교수님 안녕하세요. 확인한 메일에 회신이 늦어 죄송합니다. 지금 내용을 정리해 답변드립니다. 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-initiate-apologize-02',
    mode: 'initiate',
    scenarioId: 'professor',
    purpose: 'apologize',
    situation: '약속된 면담 시간에 늦어 교수님을 기다리게 한 사실을 확인하고 먼저 사과드림',
    candidates: tones(
      '교수님 안녕하세요. 약속된 면담 시간에 늦어 기다리게 해드렸습니다. 시간을 지키지 못해 죄송합니다.',
      '교수님 안녕하세요. 면담 시간에 늦어 소중한 시간을 기다리게 해드렸습니다. 약속된 시간을 지키지 못한 점 정말 죄송합니다.',
      '교수님 안녕하세요. 면담 시간에 늦어 기다리게 해드렸습니다. 죄송합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-reply-decline-01',
    mode: 'reply',
    scenarioId: 'professor',
    purpose: 'decline',
    situation: '조교가 선택 참여 행사에 참석할 수 있는지 물어 이번 행사에는 참여하기 어렵다고 정중히 거절함',
    receivedMessage: '이번 학과 행사에 참여할 수 있는지 알려주세요. 참여는 선택입니다.',
    candidates: tones(
      '조교님 안녕하세요. 행사 안내와 참여 제안 감사합니다. 이번 행사에는 참여하기 어려울 것 같습니다. 양해 부탁드립니다.',
      '조교님 안녕하세요. 행사 안내와 참여 기회를 주셔서 감사합니다. 다만 이번 행사에는 참여하기 어려울 것 같아 조심스럽게 말씀드립니다. 너른 양해 부탁드립니다.',
      '조교님 안녕하세요. 이번 행사에는 참여하기 어렵습니다. 참여가 어렵다는 점 전달드립니다. 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-reply-decline-02',
    mode: 'reply',
    scenarioId: 'professor',
    purpose: 'decline',
    situation: '교수님이 제안한 면담 시간에는 참여하기 어려워 해당 시간을 정중하게 거절함',
    receivedMessage: '면담은 수요일 오후 3시에 진행하면 어떨까요?',
    candidates: tones(
      '교수님 안녕하세요. 제안해 주신 수요일 오후 3시에는 면담이 어렵습니다. 해당 시간에 참여하기 어려운 점 양해 부탁드립니다. 감사합니다.',
      '교수님 안녕하세요. 면담 시간을 제안해 주셔서 감사합니다. 죄송하지만 수요일 오후 3시에는 참여하기 어려울 것 같습니다. 양해해 주시면 감사하겠습니다.',
      '교수님 안녕하세요. 수요일 오후 3시에는 면담이 어렵습니다. 해당 시간에는 참여할 수 없음을 알려드립니다. 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-initiate-decline-01',
    mode: 'initiate',
    scenarioId: 'professor',
    purpose: 'decline',
    situation: '선택 활동의 참여 여부가 확정되기 전에 이번 활동에는 참여하기 어렵다고 조교에게 먼저 알림',
    candidates: tones(
      '조교님 안녕하세요. 안내받은 선택 활동의 참여 여부를 먼저 말씀드리고자 연락드립니다. 이번 활동에는 참여하기 어렵습니다. 확인 부탁드립니다.',
      '조교님 안녕하세요. 안내받은 선택 활동을 검토한 뒤 미리 말씀드리고자 연락드립니다. 죄송하지만 이번에는 참여하기 어려울 것 같습니다. 양해 부탁드립니다.',
      '조교님 안녕하세요. 이번 선택 활동에는 참여하지 못합니다. 참여가 어렵다는 점 미리 전달드립니다. 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-initiate-decline-02',
    mode: 'initiate',
    scenarioId: 'professor',
    purpose: 'decline',
    situation: '교수님이 이전에 제안한 조교 업무 지원을 검토했지만 맡기 어렵다는 결정을 먼저 전달함',
    candidates: tones(
      '교수님 안녕하세요. 말씀해 주신 조교 업무 지원을 검토해 보았습니다. 이번에는 맡기 어려울 것 같아 먼저 말씀드립니다. 제안해 주셔서 감사합니다.',
      '교수님 안녕하세요. 조교 업무 지원 기회를 말씀해 주셔서 감사합니다. 신중히 검토했지만 이번에는 맡기 어려울 것 같아 조심스럽게 말씀드립니다. 양해 부탁드립니다.',
      '교수님 안녕하세요. 말씀해 주신 조교 업무는 이번에 맡기 어렵습니다. 검토 결과를 먼저 전달드립니다. 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-reply-question-01',
    mode: 'reply',
    scenarioId: 'professor',
    purpose: 'question',
    situation: '교수님에게 받은 과제 피드백에서 수정 범위가 불명확해 어느 부분까지 보완해야 하는지 물음',
    receivedMessage: '논지를 조금 더 보완한 뒤 다시 제출해 주세요.',
    candidates: tones(
      '교수님 안녕하세요. 보내주신 피드백 확인했습니다. 논지 보완이 서론의 문제 제기까지인지 본론의 근거 전체까지인지 여쭙고 싶습니다. 확인해 주시면 감사하겠습니다.',
      '교수님 안녕하세요. 과제 피드백을 보내주셔서 감사합니다. 수정 방향을 정확히 이해하고 싶어 여쭙는데, 논지 보완 범위가 서론의 문제 제기까지인지 본론의 근거 전체까지인지 알려주실 수 있을까요? 감사합니다.',
      '교수님 안녕하세요. 논지 보완 범위를 확인하고 싶습니다. 서론의 문제 제기와 본론의 근거 중 어디까지 수정해야 하는지 알려주시기 바랍니다. 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-reply-question-02',
    mode: 'reply',
    scenarioId: 'professor',
    purpose: 'question',
    situation: '조교에게 제출 안내를 받았지만 파일 형식이 적혀 있지 않아 허용되는 제출 형식을 물음',
    receivedMessage: '과제는 안내된 제출함에 올려주시기 바랍니다.',
    candidates: tones(
      '조교님 안녕하세요. 제출 안내 확인했습니다. 파일 형식은 문서 파일과 PDF 중 어떤 형식으로 제출하면 되는지 여쭙습니다. 감사합니다.',
      '조교님 안녕하세요. 제출 방법을 안내해 주셔서 감사합니다. 파일 형식이 따로 적혀 있지 않아 여쭙는데, 문서 파일과 PDF 중 어떤 형식으로 제출하면 될까요? 감사합니다.',
      '조교님 안녕하세요. 제출 파일 형식을 확인하고 싶습니다. 문서 파일과 PDF 중 허용되는 형식을 알려주시기 바랍니다. 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-initiate-question-01',
    mode: 'initiate',
    scenarioId: 'professor',
    purpose: 'question',
    situation: '수업에서 다룬 두 개념의 차이를 이해하기 어려워 교수님께 구분 기준을 구체적으로 질문함',
    candidates: tones(
      '교수님 안녕하세요. 수업에서 다룬 두 개념의 차이를 복습하다가 질문이 생겨 연락드립니다. 두 개념을 구분할 때 가장 중요하게 봐야 하는 기준이 무엇인지 여쭙습니다. 감사합니다.',
      '교수님 안녕하세요. 수업 내용을 복습하던 중 두 개념의 차이를 명확히 이해하지 못해 조심스럽게 질문드립니다. 두 개념을 구분할 때 우선 확인해야 하는 기준을 알려주실 수 있을까요? 감사합니다.',
      '교수님 안녕하세요. 수업에서 다룬 두 개념의 구분 기준을 질문드립니다. 가장 핵심적인 판단 기준을 알려주시기 바랍니다. 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-initiate-question-02',
    mode: 'initiate',
    scenarioId: 'professor',
    purpose: 'question',
    situation: '결석 처리와 보강 자료 확인 절차가 어떻게 되는지 조교에게 질문함',
    candidates: tones(
      '조교님 안녕하세요. 결석 처리와 보강 자료 확인 절차를 문의드리고자 연락드립니다. 각각 어떤 방식으로 확인하면 되는지 안내 부탁드립니다. 감사합니다.',
      '조교님 안녕하세요. 결석 처리와 놓친 수업의 보강 자료를 확인하는 방법이 궁금해 연락드립니다. 가능하실 때 각각의 절차를 안내해 주시면 감사하겠습니다. 감사합니다.',
      '조교님 안녕하세요. 결석 처리 방법과 보강 자료 확인 절차를 문의드립니다. 필요한 절차를 안내해 주시기 바랍니다. 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-reply-suggest-02',
    mode: 'reply',
    scenarioId: 'professor',
    purpose: 'suggest',
    situation: '교수님이 제안한 면담 시간이 어려워 다음 날 오전이라는 다른 후보를 정중하게 제안함',
    receivedMessage: '면담은 화요일 오후에 진행하면 어떨까요?',
    candidates: tones(
      '교수님 안녕하세요. 화요일 오후에는 면담이 어렵습니다. 대신 수요일 오전에 진행하는 것은 어떠신지 여쭙습니다. 감사합니다.',
      '교수님 안녕하세요. 면담 시간을 제안해 주셔서 감사합니다. 죄송하지만 화요일 오후에는 어려워, 괜찮으시다면 수요일 오전에 진행할 수 있을지 여쭙습니다. 감사합니다.',
      '교수님 안녕하세요. 화요일 오후는 어렵고 수요일 오전은 가능합니다. 수요일 오전 면담을 제안드립니다. 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-initiate-suggest-01',
    mode: 'initiate',
    scenarioId: 'professor',
    purpose: 'suggest',
    situation: '면담 목적을 밝히고 자신이 가능한 화요일 오후 2시와 목요일 오전 11시를 교수님께 제안함',
    candidates: tones(
      '교수님 안녕하세요. 과제 방향을 여쭙기 위해 면담을 요청드리고자 합니다. 저는 화요일 오후 2시와 목요일 오전 11시에 가능합니다. 두 시간 중 가능하신 때가 있는지 여쭙습니다.',
      '교수님 안녕하세요. 과제 방향과 관련해 짧게 여쭙고 싶은 내용이 있어 면담을 요청드립니다. 저는 화요일 오후 2시와 목요일 오전 11시에 가능하니, 혹시 편하신 시간이 있는지 알려주시면 감사하겠습니다. 감사합니다.',
      '교수님 안녕하세요. 과제 방향을 여쭙기 위한 면담을 요청드립니다. 화요일 오후 2시 또는 목요일 오전 11시를 제안드립니다. 가능한 시간을 알려주시기 바랍니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-initiate-suggest-02',
    mode: 'initiate',
    scenarioId: 'professor',
    purpose: 'suggest',
    situation: '과제를 자료 분석 뒤 사례 정리 순서로 진행해도 되는지 교수님께 방향을 제안하며 확인을 구함',
    candidates: tones(
      '교수님 안녕하세요. 과제 진행 방향을 확인하고자 연락드립니다. 자료를 먼저 분석한 뒤 그 결과에 맞춰 사례를 정리하는 순서로 진행하려고 합니다. 이 방향으로 진행해도 될지 여쭙습니다.',
      '교수님 안녕하세요. 과제 진행 순서를 정하는 과정에서 방향을 확인받고 싶어 연락드립니다. 자료를 먼저 분석하고 그 결과를 바탕으로 사례를 정리하는 방식으로 진행해도 괜찮을지 여쭙습니다. 감사합니다.',
      '교수님 안녕하세요. 자료 분석 후 사례를 정리하는 순서로 과제를 진행하고자 합니다. 이 방향으로 진행해도 되는지 확인 부탁드립니다. 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-reply-other-01',
    mode: 'reply',
    scenarioId: 'professor',
    purpose: 'other',
    situation: '교수님에게 과제 피드백을 받고 내용을 확인했다는 말과 감사를 전함',
    receivedMessage: '과제에서 근거를 조금 더 보완하면 좋겠습니다. 표시한 부분을 확인해 주세요.',
    candidates: tones(
      '교수님 안녕하세요. 보내주신 피드백 확인했습니다. 말씀해 주신 부분을 반영해 보완하겠습니다. 감사합니다.',
      '교수님 안녕하세요. 구체적으로 피드백해 주셔서 감사합니다. 표시해 주신 부분을 모두 확인했으며 말씀해 주신 방향에 맞춰 보완하겠습니다. 감사합니다.',
      '교수님 안녕하세요. 피드백 확인했습니다. 지적해 주신 부분을 반영해 수정하겠습니다. 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-reply-other-02',
    mode: 'reply',
    scenarioId: 'professor',
    purpose: 'other',
    situation: '조교에게 행사 안내를 받고 참석할 예정임을 간결하게 확인함',
    receivedMessage: '행사는 금요일 오후에 진행됩니다. 참석 여부를 회신해 주세요.',
    candidates: tones(
      '조교님 안녕하세요. 행사 안내 확인했습니다. 금요일 오후 행사에 참석하겠습니다. 감사합니다.',
      '조교님 안녕하세요. 행사 일정을 안내해 주셔서 감사합니다. 말씀해 주신 금요일 오후 행사에 참석하겠습니다. 감사합니다.',
      '조교님 안녕하세요. 금요일 오후 행사에 참석합니다. 참석 여부 전달드립니다. 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-professor-initiate-other-02',
    mode: 'initiate',
    scenarioId: 'professor',
    purpose: 'other',
    situation: '교수님의 피드백을 반영해 과제 수정본을 완성했다는 진행 상황을 먼저 알림',
    candidates: tones(
      '교수님 안녕하세요. 보내주신 피드백을 반영해 과제 수정본을 완성했습니다. 수정이 완료되었다는 진행 상황을 알려드립니다. 감사합니다.',
      '교수님 안녕하세요. 자세히 보내주신 피드백을 반영해 과제 수정본을 완성했습니다. 도움 주신 덕분에 수정 방향을 잡을 수 있었습니다. 완료된 진행 상황을 알려드립니다.',
      '교수님 안녕하세요. 피드백을 반영한 과제 수정본을 완성했습니다. 수정 완료 사실을 전달드립니다. 감사합니다.',
    ),
  }),
] as const satisfies readonly RetrievalCoverageDraftExampleSet[]

const seniorDraftExamples = [
  draftExample({
    exampleId: 'draft-senior-reply-ask-01',
    mode: 'reply',
    scenarioId: 'senior',
    purpose: 'ask',
    situation: '필요하면 도와주겠다는 선배의 답장에 작성한 지원서 초안을 짧게 검토해 달라고 부탁함',
    receivedMessage: '준비하다가 도움 필요하면 편하게 연락해!',
    candidates: tones(
      '감사합니다! 제가 작성한 지원서 초안이 있는데, 시간 괜찮으실 때 짧게 검토해 주실 수 있을까요?',
      '도와주신다고 말씀해 주셔서 감사합니다. 제가 작성한 지원서 초안이 있는데, 혹시 시간 괜찮으실 때 짧게 봐주실 수 있을까요?',
      '감사합니다. 작성한 지원서 초안을 짧게 검토해 주실 수 있을까요?',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-reply-ask-02',
    mode: 'reply',
    scenarioId: 'senior',
    purpose: 'ask',
    situation: '예전에 정리한 자료가 있다고 한 선배에게 공유할 수 있는 자료인지 부탁함',
    receivedMessage: '그 내용은 예전에 정리해 둔 자료가 있어.',
    candidates: tones(
      '혹시 공유 가능한 자료라면 받아볼 수 있을까요? 참고해서 준비해 보겠습니다.',
      '혹시 괜찮으시다면 정리해 두신 자료를 공유받을 수 있을까요? 준비하는 데 참고하면 큰 도움이 될 것 같습니다.',
      '공유 가능한 자료라면 보내주실 수 있을까요? 준비할 때 참고하겠습니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-initiate-ask-01',
    mode: 'initiate',
    scenarioId: 'senior',
    purpose: 'ask',
    situation: '비슷한 경험이 있는 선배에게 진로 선택에 관한 짧은 조언을 먼저 부탁함',
    candidates: tones(
      '선배님 안녕하세요. 진로 선택을 고민하다가 비슷한 경험이 있으시다고 들어 연락드렸어요. 시간 괜찮으실 때 짧게 조언을 구해도 될까요?',
      '선배님 안녕하세요. 진로 선택을 고민하던 중 선배님께서 비슷한 경험을 하셨다고 들어 조심스럽게 연락드렸습니다. 괜찮으실 때 짧게 조언을 구할 수 있을까요?',
      '선배님 안녕하세요. 진로 선택에 관해 짧게 조언을 구하고 싶습니다. 대화 가능한지 알려주실 수 있을까요?',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-initiate-ask-02',
    mode: 'initiate',
    scenarioId: 'senior',
    purpose: 'ask',
    situation: '면접을 앞두고 선배에게 예상 질문에 답하는 연습을 잠깐 도와줄 수 있는지 부탁함',
    candidates: tones(
      '선배님 안녕하세요. 면접을 앞두고 예상 질문에 답하는 연습을 하고 있어요. 시간 괜찮으실 때 잠깐 연습을 도와주실 수 있을까요?',
      '선배님 안녕하세요. 면접 준비 중인데 혼자서는 답변을 점검하기 어려워 연락드렸어요. 혹시 시간 괜찮으실 때 예상 질문 연습을 잠깐 도와주실 수 있을까요?',
      '선배님 안녕하세요. 면접 예상 질문 연습을 잠깐 도와주실 수 있을까요? 가능 여부를 알려주시면 감사하겠습니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-reply-apologize-01',
    mode: 'reply',
    scenarioId: 'senior',
    purpose: 'apologize',
    situation: '답이 늦었다는 선배의 말을 받고 늦게 회신한 점을 인정해 사과함',
    receivedMessage: '연락 확인했으면 답이라도 해주지. 기다리고 있었어.',
    candidates: tones(
      '제가 연락을 확인하고도 답이 늦었습니다. 기다리게 해서 죄송해요. 지금 바로 답드릴게요.',
      '연락을 확인하고도 바로 답드리지 못했어요. 기다리셨을 텐데 정말 죄송합니다. 지금 바로 답드릴게요.',
      '답이 늦은 건 제 잘못입니다. 기다리게 해서 죄송해요. 지금 답드리겠습니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-reply-apologize-02',
    mode: 'reply',
    scenarioId: 'senior',
    purpose: 'apologize',
    situation: '행사 준비 중 기다리고 있다는 선배의 연락을 받고 확인이 늦어 기다리게 한 점을 사과함',
    receivedMessage: '행사 준비 시작해야 하는데 아직 안 와서 기다리고 있어.',
    candidates: tones(
      '제가 연락을 늦게 확인해서 기다리게 했네요. 죄송합니다. 지금 바로 확인하고 움직일게요.',
      '연락을 늦게 확인해서 계속 기다리게 해드렸네요. 정말 죄송합니다. 지금 바로 확인하고 움직일게요.',
      '확인이 늦어 기다리게 해서 죄송합니다. 지금 바로 움직이겠습니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-initiate-apologize-01',
    mode: 'initiate',
    scenarioId: 'senior',
    purpose: 'apologize',
    situation: '선배에게 먼저 받은 연락을 뒤늦게 확인해 답장이 늦어진 점을 사과함',
    candidates: tones(
      '선배님, 보내주신 연락을 이제 확인했어요. 답장이 늦어서 죄송합니다. 지금 내용 확인해서 답드릴게요.',
      '선배님, 보내주신 연락을 늦게 확인했어요. 기다리셨을 텐데 답장이 늦어서 정말 죄송합니다. 지금 확인해서 답드릴게요.',
      '선배님, 연락 확인이 늦어 죄송합니다. 지금 확인한 내용으로 답드리겠습니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-initiate-apologize-02',
    mode: 'initiate',
    scenarioId: 'senior',
    purpose: 'apologize',
    situation: '선배에게 빌린 자료를 약속한 때 돌려주지 못한 사실을 확인하고 먼저 사과함',
    candidates: tones(
      '선배님, 빌린 자료를 약속한 때 돌려드리지 못했어요. 늦어져서 죄송합니다.',
      '선배님, 빌려주신 자료를 약속한 때 돌려드리지 못해 정말 죄송합니다. 기다리셨을 텐데 늦어진 점 사과드려요.',
      '선배님, 자료 반환이 늦어 죄송합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-reply-decline-01',
    mode: 'reply',
    scenarioId: 'senior',
    purpose: 'decline',
    situation: '선배에게 식사 모임 초대를 받았지만 이번 모임에는 참여하기 어렵다고 답함',
    receivedMessage: '이번 주에 다 같이 밥 먹는데 너도 올래?',
    candidates: tones(
      '초대해 주셔서 감사해요. 이번 모임에는 참여하기 어려울 것 같아요.',
      '같이 가자고 해주셔서 감사해요. 아쉽지만 이번 모임에는 참여하기 어려울 것 같습니다.',
      '이번 모임에는 참여하기 어렵습니다. 초대해 주셔서 감사해요.',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-reply-decline-02',
    mode: 'reply',
    scenarioId: 'senior',
    purpose: 'decline',
    situation: '선배에게 학과 행사 준비를 도와 달라는 부탁을 받았지만 이번에는 맡기 어렵다고 거절함',
    receivedMessage: '이번 학과 행사 준비를 같이 맡아줄 수 있어?',
    candidates: tones(
      '말씀해 주셔서 감사하지만 이번 행사 준비는 맡기 어려울 것 같아요.',
      '같이 해보자고 말씀해 주셔서 감사합니다. 다만 이번에는 행사 준비를 맡기 어려울 것 같아 죄송해요.',
      '이번 행사 준비는 맡기 어렵습니다. 미리 말씀드려요.',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-initiate-decline-01',
    mode: 'initiate',
    scenarioId: 'senior',
    purpose: 'decline',
    situation: '이전에 관심을 보였던 학과 활동을 다시 검토한 뒤 이번에는 참여하지 않겠다고 먼저 알림',
    candidates: tones(
      '선배님, 전에 말씀드린 학과 활동을 다시 생각해 봤어요. 이번에는 참여하지 않기로 해서 먼저 알려드립니다.',
      '선배님, 전에 관심 있다고 말씀드린 학과 활동을 다시 신중히 생각해 봤어요. 아쉽지만 이번에는 참여하지 않기로 해서 미리 알려드립니다.',
      '선배님, 검토한 결과 이번 학과 활동에는 참여하지 않겠습니다. 미리 알려드립니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-initiate-decline-02',
    mode: 'initiate',
    scenarioId: 'senior',
    purpose: 'decline',
    situation: '일정이 확정되기 전에 제안된 모임 날짜에는 참석하기 어렵다고 먼저 알림',
    candidates: tones(
      '모임 날짜 확정 전에 먼저 말씀드려요. 제안된 날짜에는 참석하기 어려울 것 같습니다.',
      '모임 날짜가 정해지기 전에 미리 말씀드리고 싶어요. 죄송하지만 지금 제안된 날짜에는 참석하기 어려울 것 같습니다.',
      '제안된 모임 날짜에는 참석하기 어렵습니다. 확정 전에 알려드립니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-reply-question-01',
    mode: 'reply',
    scenarioId: 'senior',
    purpose: 'question',
    situation: '과목 경험을 알려 준 선배의 답장에서 시험 방식에 관한 정보가 없어 추가로 물음',
    receivedMessage: '그 과목은 과제가 많지만 수업 따라가면 할 만해.',
    candidates: tones(
      '알려주셔서 감사합니다! 시험은 서술형인지 객관식인지도 여쭤봐도 될까요?',
      '과제량 알려주셔서 감사합니다. 혹시 시험이 서술형인지 객관식인지도 알려주실 수 있을까요?',
      '감사합니다. 시험이 서술형인지 객관식인지도 알려주실 수 있을까요?',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-reply-question-02',
    mode: 'reply',
    scenarioId: 'senior',
    purpose: 'question',
    situation: '지원 경험을 설명해 준 선배에게 실제 준비를 언제부터 시작했는지 추가로 물음',
    receivedMessage: '나는 서류 준비하고 면접 연습까지 해서 지원했어.',
    candidates: tones(
      '경험 알려주셔서 감사합니다. 준비는 지원하기 얼마나 전부터 시작하셨는지 궁금해요.',
      '준비 과정을 자세히 알려주셔서 감사합니다. 혹시 지원하기 얼마나 전부터 준비를 시작하셨는지도 여쭤봐도 될까요?',
      '감사합니다. 지원 준비를 언제부터 시작하셨는지 알려주실 수 있을까요?',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-initiate-question-02',
    mode: 'initiate',
    scenarioId: 'senior',
    purpose: 'question',
    situation: '학과 활동에 지원하기 전 경험이 있는 선배에게 선발 절차와 주로 하는 일을 물음',
    candidates: tones(
      '선배님 안녕하세요. 학과 활동 지원을 고민하고 있어 연락드렸어요. 선발 절차가 어떻게 되고 활동에서는 주로 어떤 일을 하는지 알려주실 수 있을까요?',
      '선배님 안녕하세요. 학과 활동에 지원하기 전에 실제 경험을 여쭤보고 싶어 연락드렸습니다. 괜찮으실 때 선발 절차와 주로 맡는 일을 알려주실 수 있을까요?',
      '선배님 안녕하세요. 학과 활동의 선발 절차와 주요 업무를 알려주실 수 있을까요? 지원 전에 확인하고 싶습니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-reply-suggest-01',
    mode: 'reply',
    scenarioId: 'senior',
    purpose: 'suggest',
    situation: '선배에게 만나자는 제안을 받고 제시된 시간 대신 다음 날 오후라는 다른 시간을 제안함',
    receivedMessage: '오늘 저녁에 잠깐 만날래?',
    candidates: tones(
      '오늘 저녁은 어려운데 내일 오후는 괜찮아요. 내일 오후에 만나는 건 어떠세요?',
      '오늘 저녁은 조금 어려울 것 같아요. 괜찮으시다면 내일 오후에 만나는 건 어떨까요?',
      '오늘 저녁은 어렵고 내일 오후는 가능합니다. 내일 오후로 제안드려요.',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-reply-suggest-02',
    mode: 'reply',
    scenarioId: 'senior',
    purpose: 'suggest',
    situation: '존댓말을 계속 써도 된다는 선배의 말에 서로 편하게 말하는 방식을 조심스럽게 제안함',
    receivedMessage: '나는 존댓말 계속 써도 괜찮아. 편한 대로 해.',
    candidates: tones(
      '말씀 감사합니다. 괜찮으시면 서로 조금 더 편하게 말해 보는 건 어떨까요?',
      '편하게 하라고 말씀해 주셔서 감사해요. 혹시 괜찮으시다면 저희 서로 조금씩 편하게 말해 볼까요?',
      '괜찮으시면 이제 서로 편하게 말해 봐요.',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-initiate-suggest-01',
    mode: 'initiate',
    scenarioId: 'senior',
    purpose: 'suggest',
    situation: '선배에게 화요일 점심과 목요일 오후 중 식사나 커피를 함께할 시간을 먼저 제안함',
    candidates: tones(
      '선배님, 시간 괜찮으시면 같이 식사나 커피 어떠세요? 저는 화요일 점심이나 목요일 오후가 가능해요.',
      '선배님, 괜찮으실 때 식사나 커피 한잔 같이하고 싶어서 연락드렸어요. 저는 화요일 점심이나 목요일 오후가 가능한데 어떠세요?',
      '선배님, 화요일 점심이나 목요일 오후에 식사나 커피를 제안드려요. 가능한 시간이 있으신가요?',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-initiate-suggest-02',
    mode: 'initiate',
    scenarioId: 'senior',
    purpose: 'suggest',
    situation: '몇 번 대화한 동기에게 앞으로 서로 편하게 말해 보자고 먼저 제안함',
    candidates: tones(
      '우리 몇 번 얘기했는데 앞으로는 서로 조금 편하게 말하는 거 어때?',
      '우리 이제 몇 번 얘기도 했는데, 괜찮으면 앞으로 서로 조금 편하게 말해 볼까?',
      '앞으로는 서로 편하게 말하자. 괜찮지?',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-reply-other-02',
    mode: 'reply',
    scenarioId: 'senior',
    purpose: 'other',
    situation: '선배가 조언을 보내 준 메시지에 내용을 확인했고 도움이 되었다는 감사의 뜻을 전함',
    receivedMessage: '내가 준비할 때 도움 됐던 방법을 정리해서 보냈어. 참고해 봐.',
    candidates: tones(
      '정리해 주신 내용 확인했어요. 준비하는 데 도움이 많이 될 것 같아요. 감사합니다!',
      '직접 정리해서 보내주셔서 정말 감사합니다. 하나씩 읽어봤는데 준비 방향을 잡는 데 큰 도움이 될 것 같아요.',
      '내용 확인했습니다. 준비에 도움이 됐어요. 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-initiate-other-01',
    mode: 'initiate',
    scenarioId: 'senior',
    purpose: 'other',
    situation: '이전에 선배에게 받은 조언을 적용한 뒤 지원 준비를 마쳤다는 결과와 근황을 먼저 공유함',
    candidates: tones(
      '선배님, 전에 해주신 조언대로 준비해서 지원을 잘 마쳤어요. 도움 주신 덕분이라 결과와 근황 먼저 공유드려요!',
      '선배님, 전에 해주신 조언을 하나씩 적용해서 지원 준비를 잘 마쳤어요. 덕분에 방향을 잡을 수 있어서 감사한 마음에 근황을 먼저 전해요.',
      '선배님, 조언해 주신 대로 준비해 지원을 마쳤습니다. 도움 주셔서 감사합니다.',
    ),
  }),
  draftExample({
    exampleId: 'draft-senior-initiate-other-02',
    mode: 'initiate',
    scenarioId: 'senior',
    purpose: 'other',
    situation: '졸업 소식을 들은 선배에게 축하의 뜻을 먼저 전함',
    candidates: tones(
      '선배님, 졸업 소식 들었어요! 정말 축하드립니다. 앞으로도 좋은 일 가득하시길 바랄게요.',
      '선배님, 졸업하신다는 소식 듣고 축하드리고 싶어 연락드렸어요. 그동안 정말 수고 많으셨고 앞으로도 좋은 일만 가득하시길 바랍니다!',
      '선배님, 졸업을 진심으로 축하드립니다. 앞으로의 시작도 응원하겠습니다.',
    ),
  }),
] as const satisfies readonly RetrievalCoverageDraftExampleSet[]

const friendDraftExamples = [
  draftExample({
    exampleId: 'draft-friend-reply-ask-01',
    mode: 'reply',
    scenarioId: 'friend',
    purpose: 'ask',
    situation: '필요하면 연락하라는 친구의 말에 잠깐 통화하며 자신의 이야기를 들어 달라고 부탁함',
    receivedMessage: '힘들면 언제든 연락해. 내가 들어줄게.',
    candidates: tones(
      '고마워. 지금 잠깐 통화하면서 내 이야기 좀 들어줄 수 있어?',
      '그렇게 말해줘서 고마워. 괜찮으면 지금 잠깐 통화하면서 내 이야기 좀 들어줄 수 있을까?',
      '고마워. 지금 잠깐 통화하면서 내 이야기 들어줘.',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-reply-ask-02',
    mode: 'reply',
    scenarioId: 'friend',
    purpose: 'ask',
    situation: '어떤 도움이 필요한지 묻는 친구에게 혼자 가기 부담스러운 일정에 함께 가 달라고 부탁함',
    receivedMessage: '내가 뭐 도와주면 돼?',
    candidates: tones(
      '혼자 가기 조금 부담스러운 일정이 있는데 같이 가줄 수 있어?',
      '물어봐 줘서 고마워. 혼자 가기 조금 부담스러운 일정이 있는데, 괜찮으면 같이 가줄 수 있을까?',
      '그 일정에 같이 가줄 수 있는지 알려줘.',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-initiate-ask-01',
    mode: 'initiate',
    scenarioId: 'friend',
    purpose: 'ask',
    situation: '고민이 있어 친구에게 잠깐 통화하며 이야기를 들어줄 수 있는지 먼저 부탁함',
    candidates: tones(
      '나 지금 고민이 좀 있는데 잠깐 통화하면서 이야기 들어줄 수 있어?',
      '나 고민이 좀 있어서 그런데, 괜찮으면 잠깐 통화하면서 이야기 들어줄 수 있을까?',
      '나 고민이 있어. 잠깐 통화하면서 이야기 들어줘.',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-initiate-ask-02',
    mode: 'initiate',
    scenarioId: 'friend',
    purpose: 'ask',
    situation: '혼자 가기 부담스러운 일정에 친구가 함께 가 줄 수 있는지 먼저 부탁함',
    candidates: tones(
      '혼자 가기 조금 부담스러운 일정이 있어. 혹시 같이 가줄 수 있어?',
      '혼자 가기 조금 부담스러운 일정이 있는데, 괜찮으면 같이 가줄 수 있을까?',
      '혼자 가기 부담스러운 일정이 있어. 같이 가줄 수 있는지 알려줘.',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-reply-apologize-02',
    mode: 'reply',
    scenarioId: 'friend',
    purpose: 'apologize',
    situation: '약속을 잊은 것 같다는 친구의 연락을 받고 약속을 확인하지 못한 점을 인정해 사과함',
    receivedMessage: '우리 약속한 거 잊은 거 아니지? 계속 연락이 없네.',
    candidates: tones(
      '내가 약속을 제대로 확인하지 못했어. 연락 기다리게 해서 미안해. 지금 바로 확인할게.',
      '내가 약속을 제대로 확인하지 못했어. 계속 기다렸을 텐데 정말 미안해. 지금 바로 확인할게.',
      '약속을 확인하지 못한 건 내 잘못이야. 기다리게 해서 미안해. 지금 확인할게.',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-initiate-apologize-01',
    mode: 'initiate',
    scenarioId: 'friend',
    purpose: 'apologize',
    situation: '친구의 메시지를 보고도 답을 미뤄 회신이 늦어진 점을 먼저 사과함',
    candidates: tones(
      '메시지 보고도 답을 미루다가 너무 늦었어. 기다리게 해서 미안해. 지금 제대로 답할게.',
      '메시지를 보고도 바로 답하지 못하고 계속 미뤘어. 기다렸을 텐데 정말 미안해. 지금 제대로 답할게.',
      '답을 미뤄서 늦었어. 기다리게 해서 미안해. 지금 답할게.',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-initiate-apologize-02',
    mode: 'initiate',
    scenarioId: 'friend',
    purpose: 'apologize',
    situation: '친구가 개인적으로 말한 이야기를 다른 자리에서 언급한 사실을 알고 먼저 사과함',
    candidates: tones(
      '네가 개인적으로 말한 이야기를 내가 다른 자리에서 언급했어. 신뢰를 지키지 못해서 미안해.',
      '네가 믿고 말해준 이야기를 내가 다른 자리에서 언급했어. 얼마나 불편하고 속상했을지 생각하니 정말 미안해.',
      '네 개인적인 이야기를 다른 자리에서 말한 건 내 잘못이야. 미안해.',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-reply-decline-01',
    mode: 'reply',
    scenarioId: 'friend',
    purpose: 'decline',
    situation: '친구가 이번 주에 만나자고 제안했지만 이번 만남은 어렵다고 답함',
    receivedMessage: '이번 주에 시간 되면 우리 만날래?',
    candidates: tones(
      '이번 주에는 만나기 어려울 것 같아. 이번 만남은 못 갈 것 같아.',
      '만나자고 해줘서 고마워. 아쉽지만 이번 주에는 만나기 어려울 것 같아.',
      '이번 주 만남은 어려워. 이번에는 못 갈 것 같아.',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-reply-decline-02',
    mode: 'reply',
    scenarioId: 'friend',
    purpose: 'decline',
    situation: '친구가 물건을 빌려 달라고 부탁했지만 이번에는 빌려주기 어렵다고 거절함',
    receivedMessage: '네 물건 이번에 잠깐 빌려도 돼?',
    candidates: tones(
      '이번에는 그 물건을 빌려주기 어려울 것 같아. 미안해.',
      '필요한 건 알겠는데 이번에는 그 물건을 빌려주기 어려울 것 같아. 미안해.',
      '이번에는 그 물건을 빌려줄 수 없어. 미안해.',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-initiate-decline-01',
    mode: 'initiate',
    scenarioId: 'friend',
    purpose: 'decline',
    situation: '이미 함께 논의하던 만남에 참여하기 어렵다는 결정을 친구가 다시 묻기 전에 먼저 알림',
    candidates: tones(
      '전에 이야기하던 만남 생각해 봤는데 이번에는 참여하기 어려울 것 같아. 미리 알려.',
      '전에 이야기하던 만남을 다시 생각해 봤어. 미안하지만 이번에는 참여하기 어려울 것 같아서 먼저 알려.',
      '전에 이야기한 만남에는 참여하지 못해. 결정한 내용 먼저 알려.',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-initiate-decline-02',
    mode: 'initiate',
    scenarioId: 'friend',
    purpose: 'decline',
    situation: '친구와 이야기한 장거리 일정에는 참여하지 않기로 했다고 먼저 알림',
    candidates: tones(
      '같이 가자고 했던 장거리 일정 생각해 봤는데 나는 참여하지 않기로 했어. 먼저 알려.',
      '같이 가자고 한 장거리 일정을 생각해 봤어. 미안하지만 나는 이번에는 참여하지 않기로 해서 먼저 알려.',
      '장거리 일정에는 참여하지 않기로 했어. 미리 알려.',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-reply-question-01',
    mode: 'reply',
    scenarioId: 'friend',
    purpose: 'question',
    situation: '친구의 약속 제안에 장소와 시간이 빠져 있어 어디서 언제 만날지 물음',
    receivedMessage: '우리 이번에 만나서 같이 놀자!',
    candidates: tones(
      '좋아! 언제 어디서 만날 생각이야?',
      '좋아, 같이 만나자! 혹시 언제 어디서 만날지 생각해 둔 게 있어?',
      '좋아. 만날 시간과 장소를 알려줘.',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-reply-question-02',
    mode: 'reply',
    scenarioId: 'friend',
    purpose: 'question',
    situation: '고민이 있다고만 말한 친구에게 부담을 주지 않으면서 어떤 일이 있었는지 물음',
    receivedMessage: '나 요즘 고민이 좀 있어.',
    candidates: tones(
      '무슨 일 있었어? 말하고 싶으면 들어줄게.',
      '무슨 일이 있었는지 물어봐도 될까? 지금 말하기 괜찮으면 천천히 들어줄게.',
      '어떤 일이 있었는지 말해줄래? 내가 들을게.',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-initiate-question-01',
    mode: 'initiate',
    scenarioId: 'friend',
    purpose: 'question',
    situation: '중요한 시험을 치른 친구에게 시험이 어떻게 되었는지 먼저 물음',
    candidates: tones(
      '오늘 시험 본 거 어땠어? 잘 마쳤는지 궁금해.',
      '오늘 중요한 시험 본다고 했지? 괜찮으면 시험이 어땠는지 이야기해 줄래?',
      '오늘 시험 어떻게 됐어? 어땠는지 알려줘.',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-initiate-question-02',
    mode: 'initiate',
    scenarioId: 'friend',
    purpose: 'question',
    situation: '자신이 작성한 초안에 대해 친구의 솔직한 의견을 들을 수 있는지 먼저 물음',
    candidates: tones(
      '내가 작성한 초안이 있는데 읽어보고 솔직한 의견 줄 수 있어?',
      '내가 작성한 초안이 있는데, 괜찮으면 읽어보고 솔직하게 어떤지 말해줄 수 있을까?',
      '내 초안 읽어보고 솔직한 의견을 알려줘.',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-reply-suggest-01',
    mode: 'reply',
    scenarioId: 'friend',
    purpose: 'suggest',
    situation: '친구가 주말에 만나자고 제안해 주말 대신 다음 주 평일 저녁에 산책하자고 제안함',
    receivedMessage: '이번 주말에 만나서 놀까?',
    candidates: tones(
      '이번 주말은 어려운데 다음 주 평일 저녁에 산책하는 건 어때?',
      '이번 주말은 조금 어려울 것 같아. 괜찮으면 다음 주 평일 저녁에 같이 산책하는 건 어떨까?',
      '이번 주말은 어렵고 다음 주 평일 저녁은 가능해. 그때 산책하자.',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-reply-suggest-02',
    mode: 'reply',
    scenarioId: 'friend',
    purpose: 'suggest',
    situation: '친구가 무엇을 먹을지 물어 한식과 샌드위치라는 두 선택지를 제안함',
    receivedMessage: '우리 뭐 먹을까?',
    candidates: tones(
      '한식이나 샌드위치 중에 고르는 건 어때?',
      '나는 한식이나 샌드위치가 좋을 것 같은데, 둘 중에 같이 골라볼까?',
      '한식이랑 샌드위치 중에서 고르자. 어떤 게 좋아?',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-initiate-suggest-02',
    mode: 'initiate',
    scenarioId: 'friend',
    purpose: 'suggest',
    situation: '시험 기간에 각자 공부한 뒤 저녁에 서로 진행 상황을 확인하자고 친구에게 먼저 제안함',
    candidates: tones(
      '시험 기간 동안 각자 공부하고 저녁에 진행 상황 한 번씩 확인하는 거 어때?',
      '시험 기간에 혼자 하다 보면 늘어질 수 있으니까, 괜찮으면 각자 공부하고 저녁에 진행 상황을 같이 확인해 볼까?',
      '각자 공부하고 저녁에 진행 상황을 확인하자. 서로 한 번씩 알려주는 방식으로 하자.',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-reply-other-01',
    mode: 'reply',
    scenarioId: 'friend',
    purpose: 'other',
    situation: '친구에게 생일 축하와 선물을 받은 메시지에 기쁨과 감사를 전함',
    receivedMessage: '생일 축하해! 작은 선물도 보냈어.',
    candidates: tones(
      '축하해 줘서 고마워! 선물도 정말 마음에 들어.',
      '생일 기억하고 축하해 준 것도 고마운데 선물까지 보내줘서 정말 감동이야. 잘 쓸게!',
      '축하와 선물 모두 고마워. 잘 쓸게!',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-reply-other-02',
    mode: 'reply',
    scenarioId: 'friend',
    purpose: 'other',
    situation: '힘들 때 곁에 있겠다는 친구의 말에 고마움과 현재 위로받은 마음을 답함',
    receivedMessage: '힘들 때 혼자 있지 말고 연락해. 내가 옆에 있을게.',
    candidates: tones(
      '그렇게 말해줘서 고마워. 네 말 덕분에 마음이 조금 놓였어.',
      '내 옆에 있어주겠다고 말해줘서 정말 고마워. 지금 그 말이 큰 위로가 됐고 마음이 조금 놓였어.',
      '곁에 있겠다고 해줘서 고마워. 네 말에 위로받았어.',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-initiate-other-01',
    mode: 'initiate',
    scenarioId: 'friend',
    purpose: 'other',
    situation: '힘든 이야기를 여러 번 들어준 친구에게 구체적인 고마움을 먼저 전함',
    candidates: tones(
      '내가 힘들 때마다 이야기 들어줘서 정말 고마워. 네 덕분에 버틸 수 있었어.',
      '내가 힘들 때마다 판단하지 않고 끝까지 이야기 들어줘서 정말 고마워. 네가 곁에 있어준 덕분에 많이 버틸 수 있었어.',
      '힘들 때마다 내 이야기 들어줘서 고마워. 네 도움이 정말 컸어.',
    ),
  }),
  draftExample({
    exampleId: 'draft-friend-initiate-other-02',
    mode: 'initiate',
    scenarioId: 'friend',
    purpose: 'other',
    situation: '관계에서 대화가 끊길 때 서운했던 마음과 앞으로 솔직하게 이야기하고 싶다는 바람을 공격하지 않고 먼저 표현함',
    candidates: tones(
      '우리 대화가 갑자기 끊길 때 나는 조금 서운했어. 앞으로는 서로 마음에 걸리는 게 있으면 솔직하게 이야기했으면 좋겠어.',
      '이 말을 꺼내는 게 조심스럽지만, 우리 대화가 갑자기 끊길 때 나는 조금 서운했어. 괜찮다면 앞으로 마음에 걸리는 게 있을 때 서로 솔직하게 이야기해 보면 좋겠어.',
      '대화가 갑자기 끊길 때 나는 서운해. 앞으로 마음에 걸리는 건 서로 솔직하게 이야기했으면 해.',
    ),
  }),
] as const satisfies readonly RetrievalCoverageDraftExampleSet[]

export const retrievalCoverageCandidateDraft = [
  ...groupworkDraftExamples,
  ...professorDraftExamples,
  ...seniorDraftExamples,
  ...friendDraftExamples,
] as const satisfies readonly RetrievalCoverageDraftExampleSet[]
