/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#0b1c30',
        'on-secondary-container': '#54647a',
        'surface-tint': '#0053db',
        error: '#ba1a1a',
        'tertiary-fixed': '#ffdbcd',
        'secondary-fixed-dim': '#b7c8e1',
        'surface-container-low': '#f2f3ff',
        surface: '#faf8ff',
        'primary-fixed': '#dbe1ff',
        'surface-variant': '#dae2fd',
        'on-primary-container': '#eeefff',
        'surface-container-highest': '#dae2fd',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#eef0ff',
        'on-secondary-fixed-variant': '#38485d',
        'secondary-fixed': '#d3e4fe',
        'on-surface': '#131b2e',
        'on-primary-fixed': '#00174b',
        'surface-container-high': '#e2e7ff',
        secondary: '#505f76',
        'on-background': '#131b2e',
        'surface-container': '#eaedff',
        'on-primary-fixed-variant': '#003ea8',
        'secondary-container': '#d0e1fb',
        'surface-dim': '#d2d9f4',
        'on-tertiary-fixed': '#360f00',
        'on-tertiary-fixed-variant': '#7d2d00',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        outline: '#737686',
        'on-surface-variant': '#434655',
        'outline-variant': '#c3c6d7',
        'on-secondary': '#ffffff',
        'error-container': '#ffdad6',
        'primary-fixed-dim': '#b4c5ff',
        'tertiary-container': '#bc4800',
        'primary-container': '#2563eb',
        primary: '#004ac6',
        'on-error': '#ffffff',
        background: '#faf8ff',
        'inverse-primary': '#b4c5ff',
        'surface-bright': '#faf8ff',
        'inverse-surface': '#283044',
        'on-primary': '#ffffff',
        tertiary: '#943700',
        'on-tertiary-container': '#ffede6',
        'tertiary-fixed-dim': '#ffb596',
        // 2026-07 결정 (newssist-design 스킬) — 버튼/네비/아바타 등 UI 크롬 전용
        'btn-gray': '#E4E6EC',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        unit: '4px',
        'stack-sm': '8px',
        'stack-md': '16px',
        gutter: '16px',
        'container-padding': '24px',
        'stack-lg': '32px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'Pretendard', 'sans-serif'],
        'headline-sm': ['Inter', 'Pretendard', 'sans-serif'],
        caption: ['Inter', 'Pretendard', 'sans-serif'],
        'display-lg': ['Inter', 'Pretendard', 'sans-serif'],
        'headline-md': ['Inter', 'Pretendard', 'sans-serif'],
        'body-md': ['Inter', 'Pretendard', 'sans-serif'],
        'label-mono': ['JetBrains Mono', 'Pretendard', 'monospace'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-mono': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
