spring:

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true

    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug

seoul:
  api:
    key: ${SEOUL_API_KEY}
