export const episodes = [
  {
    id: 'relationships',
    time: '1:20 AM – 1:34 AM',
    topic: 'relationships',
    tab: 'recent',
    submerged: false,
    preview: "Let's pick this back up whenever you're ready.",
    messages: [{ from: 'ai', text: "Let's pick this back up." }],
  },
  {
    id: 'selfdoubt',
    time: '2:14 AM – 3:27 AM',
    topic: 'Self-doubt',
    tab: 'recent',
    submerged: true,
    preview: "I keep having this thought lately, and I wonder if it's just me…",
    summary: '2:14 AM, later than usual',
    messages: [
      { from: 'user', text: "I keep having this thought lately, and I wonder if it's just me…" },
      { from: 'user', text: "Honestly, I've been feeling really unsure of myself. But I couldn't tell anyone." },
    ],
  },
  {
    id: 'identity',
    time: '3:40 AM – 4:05 AM',
    topic: 'Identity',
    tab: 'recent',
    submerged: true,
    preview: 'I acted fine all day, but right now, at this hour, I just fall apart.',
    summary: '3:40 AM, later than usual',
    messages: [
      { from: 'user', text: 'I acted fine all day, but right now, at this hour, I just fall apart.' },
      { from: 'ai', text: "It sounds like you've been holding it together all day. You can let it go for now." },
    ],
  },
  {
    id: 'meeting',
    time: '9:12 AM – 9:24 AM',
    topic: 'Meeting notes',
    tab: 'recent',
    submerged: false,
    preview: 'Can you help me organize the project deadline schedule?',
    messages: [
      { from: 'user', text: 'Can you help me organize the project deadline schedule?' },
      { from: 'ai', text: "Sure — share the project name and estimated time for each task, and I'll put together a timeline." },
    ],
  },
  {
    id: 'schedule',
    time: '10:40 AM – 10:47 AM',
    topic: 'Schedule planning',
    tab: 'history',
    submerged: false,
    preview: 'Can you make this email sound more polite?',
    messages: [{ from: 'user', text: 'Can you make this email sound more polite?' }],
  },
];
