import Link from 'next/link';
import { requireSession } from '../../../../web/auth/session';
import { getCoreAdapter } from '../../../../web/adapters/core/registry';
import { ErrorState } from '../../../../web/components/error-state';
import { DailyGoalForm } from '../../../../web/components/client/daily-goal-form';
import { StudyTimer } from '../../../../web/components/client/study-timer';
import { VerificationForm } from '../../../../web/components/client/verification-form';
import { Progress } from '../../../../web/components/server/progress';
import { MissionRealtime } from '../../../../web/components/client/mission-realtime';
export default async function StudyPage({ params }: { params: Promise<{ participationId: string }> }) { const { participationId } = await params; const ctx = await requireSession(`/study/${participationId}`); const adapter = getCoreAdapter(); const [workspaceResult, progressResult, missionResult] = await Promise.all([adapter.getStudyWorkspace(ctx, participationId), adapter.getProgress(ctx, participationId), adapter.getActiveMission(ctx, participationId)]); if (!workspaceResult.ok) return <main><ErrorState message="학습 공간을 열지 못했습니다." traceId={workspaceResult.error.traceId} /></main>; const workspace = workspaceResult.value; return <main><section className="glass plane"><p className="eyebrow">Today · {workspace.localDate}</p><span className="status">{workspace.survivalStatus === 'alive' ? '생존 중' : workspace.survivalStatus}</span><h1>{workspace.challengeTitle}</h1><p>오늘 마감 {new Date(workspace.deadlineAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</p></section>{progressResult.ok && <Progress progress={progressResult.value} />}{missionResult.ok && missionResult.value && <aside className="glass card"><p className="eyebrow">Surprise mission</p><h2>{missionResult.value.title}</h2><p>{missionResult.value.description}</p><MissionRealtime challengeId={workspace.challengeId} /></aside>}<div className="two-col"><section className="glass card"><h2>1. 오늘의 목표</h2><DailyGoalForm participationId={participationId} date={workspace.localDate} defaultGoal={workspace.progress.goal} /></section><section className="glass card"><h2>2. 집중 시간</h2><StudyTimer participationId={participationId} date={workspace.localDate} confirmedSeconds={workspace.progress.confirmedSeconds} requiredSeconds={workspace.progress.requiredSeconds} /></section></div><section className="glass plane"><h2>3. 회고와 생존 인증</h2><p className="muted">증빙은 비공개로 저장되며 권한을 확인한 뒤에만 접근합니다.</p><VerificationForm participationId={participationId} date={workspace.localDate} /></section><div className="meta"><Link className="button button-secondary" href={`/study/${participationId}/leaderboard`}>생존 순위 보기</Link><Link className="button button-secondary" href={`/study/${participationId}/report`}>학습 리포트</Link></div></main> }
