export const ANALYSIS_LOG_STEPS = [
  "INITIALIZING ENGINE...",
  "SCANNING FILE STRUCTURE...",
  "ANALYZING PACKAGE.JSON",
  "EXTRACTING DEPENDENCIES... [OK]",
  "IDENTIFYING KEY ALGORITHMS...",
  "HEURISTIC MAPPING STARTED",
  "LOCATING LOGIC BOTTLENECKS...",
  "SCANNING REPO_ROOT/SRC/LIBS...",
  "PROCESSING DATA FLOWS_",
  "IDENTIFYING DESIGN PATTERNS...",
  "COMPUTING COMPLEXITY METRICS...",
  "MAPPING DATA STRUCTURES...",
  "EVALUATING PERFORMANCE OVERHEAD...",
  "CHECKING SECURITY VULNERABILITIES...",
  "OPTIMIZING ANALYSIS PIPELINE...",
  "REFLECTING SOFT DATA INPUTS...",
  "BUILDING INSIGHT REPORT...",
] as const;

export function getAnalysisLogMessage(step: string, isComplete: boolean) {
  return `> ${step}${isComplete && !step.endsWith("[OK]") ? " [OK]" : ""}`;
}
